    <section class="content-header">
      <h1><?php echo (! isset($this->edit))?'Save':'Edit';?> Customer</h1>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="box box-primary">
            <!-- /.box-header -->
            <!-- form start -->
            <form role="form" action="<?=$this->url('customers/save')?>" method="post">
            <?php if(isset($this->edit)) {?>
            	<input type="hidden" name="edit" value="<?=$this->SecureKey()?>">
                <input type="hidden" name="customer[id]" value="<?php if(isset($this->edit)) { echo $this->customer->getId();} ?>">
            <?php } ?>
               <input type="hidden" name="postaction" value="<?php echo (! isset($this->edit))?'new':'edit';?>">
              <div class="box-body">
                <div class="form-group">
                  <label for="customername">Customer Name</label>
                  <input type="text" name="customer[name]" class="form-control" id="customername" placeholder="Customer Name" required value="<?php if(isset($this->edit)) { echo $this->customer->getName();} ?>">
                </div>
                <div class="form-group">
                  <label for="customername">Customer Id</label>
                  <input type="text" name="customer[customerid]" class="form-control" id="customerid" placeholder="Customer Id" maxlength="15" value="<?php if(isset($this->edit)) { echo $this->customer->getCustomerId();} ?>">
                </div>
                <div class="form-group">
                  <label for="company">Company Name</label>
                  <input type="text" name="customer[company]" class="form-control" id="companyname" placeholder="Company Name" required value="<?php if(isset($this->edit)) { echo $this->customer->getCompany();} ?>">
                </div>
                <div class="form-group">
                  <label for="phone">Phone</label>
                  <input type="text" name="customer[phone]" class="form-control" id="phone" placeholder="Phone" required value="<?php if(isset($this->edit)) { echo $this->customer->getPhone();} ?>">
                </div>
              </div>
              <!-- /.box-body -->

              <div class="box-footer">
                <button type="submit" class="btn btn-primary"><?php echo (! isset($this->edit))?'Save':'Edit';?> Customer</button>
              </div>
            </form>
          </div>
          <!-- /.box -->

        </div>
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->